Repository EntryDSM/Husky, pull requests merged in 2020-08, with the labels that each got.

#20 INFO - Users/me , Users/me/type API&Test
  build.gradle
  core/src/main/java/kr/hs/entrydsm/husky/config/JpaConfig.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/Application.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/BaseTimeEntity.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/GEDApplication.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/GeneralApplication.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/GraduatedApplication.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/UnGraduatedApplication.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/users/Status.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/users/User.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/users/repositories/UserRepository.java
  core/src/main/java/kr/hs/entrydsm/husky/error/GlobalExceptionHandler.java
  core/src/main/java/kr/hs/entrydsm/husky/error/exception/ErrorCode.java
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/exception/ApplicationNotFoundException.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/controller/UserController.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/SelectTypeRequest.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/SetUserInfoRequest.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/UserInfoResponse.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/UserTypeResponse.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/exception/BadRequestException.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/exception/SchoolNotFoundException.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/exception/UserNotFoundException.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/service/UserInfoService.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/service/UserTypeService.java
  info/src/test/java/kr/hs/entrydsm/husky/UserInfoApiTest.java
  info/src/test/java/kr/hs/entrydsm/husky/UserTypeApiTest.java
  info/src/test/resources/application-test.properties
Labels: enhancement

#24 INFO - Applications API&TEST
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/Application.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/GeneralApplication.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/users/User.java
  core/src/main/java/kr/hs/entrydsm/husky/error/exception/BadRequestException.java
  core/src/main/java/kr/hs/entrydsm/husky/error/exception/ErrorCode.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/controller/ApplicationController.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/dto/IntroResponse.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/dto/PlanResponse.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/dto/ScoreResponse.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/dto/SetDocsRequest.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/dto/SetGedScoreRequest.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/dto/SetScoreRequest.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/exception/ApplicationTypeUnmatchedException.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/service/ApplicationService.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/schedule/dto/CreateScheduleRequest.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/SelectTypeRequest.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/SetUserInfoRequest.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/UserInfoResponse.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/UserStatusResponse.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/dto/UserTypeResponse.java
  info/src/test/java/kr/hs/entrydsm/husky/ApplicationApiTest.java
Labels: enhancement

#16 CI/CD Pipeline: 오류 수정
  .github/workflows/deploy-to-registry.yml
  Dockerfile
Labels: bug

#25 INFO - Process API&TEST
  core/src/main/java/kr/hs/entrydsm/husky/entities/applications/GeneralApplication.java
  core/src/main/java/kr/hs/entrydsm/husky/entities/users/User.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/process/controller/ProcessController.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/process/dto/ProcessResponse.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/process/service/ProcessService.java
  info/src/test/java/kr/hs/entrydsm/husky/ApplicationApiTest.java
  info/src/test/java/kr/hs/entrydsm/husky/UserInfoApiTest.java
  info/src/test/java/kr/hs/entrydsm/husky/UserTypeApiTest.java
Labels: enhancement

#23 Config: 배포를 위한 설정 파일 추가
  auth/src/main/java/kr/hs/entrydsm/husky/controllers/UserAuthController.java
  gradle/wrapper/gradle-wrapper.properties
  husky/src/main/resources/application.yml
  info/src/main/java/kr/hs/entrydsm/husky/domain/schedule/service/ScheduleService.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/user/controller/UserInfoController.java
  info/src/test/resources/application-test.properties
  info/src/test/resources/application-test.yml
Labels: enhancement

#26 INFO - Fix Redis settings
  info/src/main/java/kr/hs/entrydsm/husky/domain/schedule/config/RedisRepositoryConfig.java
  info/src/test/java/kr/hs/entrydsm/husky/ScheduleApiTest.java
  info/src/test/java/kr/hs/entrydsm/husky/ScheduleRepositoryTest.java
  info/src/test/resources/application-test.yml
Labels: bug, enhancement

#22 Auth Test Code
  auth/src/main/java/kr/hs/entrydsm/husky/config/RedisConfig.java
  auth/src/main/java/kr/hs/entrydsm/husky/config/RedisRepositoryConfig.java
  auth/src/main/java/kr/hs/entrydsm/husky/controllers/AuthController.java
  auth/src/main/java/kr/hs/entrydsm/husky/controllers/UserAuthController.java
  auth/src/main/java/kr/hs/entrydsm/husky/dto/request/AccountRequest.java
  auth/src/main/java/kr/hs/entrydsm/husky/dto/request/ChangePasswordRequest.java
  auth/src/main/java/kr/hs/entrydsm/husky/dto/request/VerifyCodeRequest.java
  auth/src/main/java/kr/hs/entrydsm/husky/dto/response/TokenResponse.java
  auth/src/main/java/kr/hs/entrydsm/husky/entities/refresh_token/RefreshTokenRepository.java
  auth/src/main/java/kr/hs/entrydsm/husky/entities/verification/EmailVerificationRepository.java
  auth/src/main/java/kr/hs/entrydsm/husky/service/auth/AuthService.java
  auth/src/main/java/kr/hs/entrydsm/husky/service/auth/AuthServiceImpl.java
  auth/src/main/java/kr/hs/entrydsm/husky/service/user/UserService.java
  auth/src/main/java/kr/hs/entrydsm/husky/service/user/UserServiceImpl.java
  auth/src/main/resources/application.yml
  auth/src/test/java/kr/hs/entrydsm/husky/user/AuthApiTest.java
  auth/src/test/java/kr/hs/entrydsm/husky/user/UserApiTest.java
  auth/src/test/resources/application-test.yml
  build.gradle
Labels: enhancement

#28 Grade Calc: 성적산출 로직 구현
  core/src/main/java/kr/hs/entrydsm/husky/entities/users/User.java
  grade/src/main/java/kr/hs/entrydsm/husky/domain/grade/service/GradeCalcServiceImpl.java
  grade/src/main/java/kr/hs/entrydsm/husky/domain/grade/util/GradeUtil.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/application/service/ApplicationService.java
  info/src/main/java/kr/hs/entrydsm/husky/domain/process/service/ProcessService.java
Labels: enhancement
