Repository EntryDSM/Husky, pull requests merged in 2020-10, with the labels that each got.

#71 Fix validation
  src/main/java/kr/hs/entrydsm/husky/domain/grade/util/GradeUtil.java
  src/main/java/kr/hs/entrydsm/husky/domain/process/service/ProcessService.java
  src/main/java/kr/hs/entrydsm/husky/domain/process/service/ProcessServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/global/util/Validator.java
Labels: fix

#78 [REFACTOR] Docx4J to iText7
  build.gradle
  src/main/java/kr/hs/entrydsm/husky/domain/image/service/ImageUrlServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/config/PdfConfig.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/HtmlConverter.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/processor/TemplateProcessor.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/util/FontLoader.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/util/PdfMergeUtil.java
  src/main/java/kr/hs/entrydsm/husky/global/config/security/ExceptionHandlerFilter.java
  src/main/resources/application.yml
  src/main/resources/templates/admission_agreement.html
  src/main/resources/templates/application.docx
  src/main/resources/templates/application_for_admission.html
  src/main/resources/templates/common_application.docx
  src/main/resources/templates/ged_application.docx
  src/main/resources/templates/introduction.html
  src/main/resources/templates/nonsmoking.html
  src/main/resources/templates/preview/application.docx
  src/main/resources/templates/preview/common_application.docx
  src/main/resources/templates/preview/ged_application.docx
  src/main/resources/templates/recommendation.html
Labels: performance issue

#80 [FIX] 마이스터 전형 선택시 학교장 추천서에 중복 표기되는 오류 수정
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/User.java
Labels: bug

#77 GET Status API 분리
  src/main/java/kr/hs/entrydsm/husky/domain/user/controller/UserInfoController.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/dto/UserPassResponse.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/dto/UserStatusResponse.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/exception/ProcessNotCompletedException.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/exception/ScheduleNotFoundException.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/exception/ScheduleNotStartedException.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/husky/global/util/Validator.java
Labels: fix

#84 [FIX] 자기소개서/학업소개서 입력 칸 개행 적용
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
  src/main/resources/templates/introduction.html
Labels: bug

#89 [FIX] 회원가입 로직에 Status 생성 로직 추가
  src/main/java/kr/hs/entrydsm/husky/domain/auth/service/user/UserServiceImpl.java
Labels: fix

#91 FIX: 원서출력 시 성별이 null인 경우 NullPointerException 발생
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/husky/global/util/Validator.java
Labels: bug
