Repository EntryDSM/Husky, pull requests merged in 2020-09, with the labels that each got.

#35 [FIX] 지원자 사진을 null로 설정할 수 있게끔 변경
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/User.java
Labels: bug

#37 Info fix: CD 파이프라인 수정
  .github/workflows/deploy-to-registry.yml
Labels: bug

#39 PDF 최적화: 누락된 정보가 있어도 미리보기가 가능하도록 수정
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/GeneralApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/controller/PDFExportController.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/husky/global/config/security/SecurityConfig.java
  src/main/resources/templates/application.docx
  src/main/resources/templates/common_application.docx
  src/main/resources/templates/ged_application.docx
  src/main/resources/templates/preview/application.docx
  src/main/resources/templates/preview/common_application.docx
  src/main/resources/templates/preview/ged_application.docx
Labels: enhancement

#40 GET info API 수정
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/GeneralApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/GraduatedApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/UnGraduatedApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/dto/SetDocsRequest.java
  src/main/java/kr/hs/entrydsm/husky/domain/image/service/S3ImageServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/UserTypeService.java
  src/main/java/kr/hs/entrydsm/husky/global/util/Validator.java
Labels: fix

#43 FIX OneToOne LazyLoading: 지연 로딩 적용
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/CalculatedScore.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/GEDApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/GraduatedApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/UnGraduatedApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/adapter/GeneralApplicationAdapter.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/repositories/GEDApplicationRepository.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/repositories/GeneralApplicationRepository.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/repositories/GeneralApplicationRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/repositories/GraduatedApplicationRepository.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/repositories/UnGraduatedApplicationRepository.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/repositories/async/GeneralApplicationAsyncRepository.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/repositories/async/GeneralApplicationAsyncRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/service/ApplicationService.java
  src/main/java/kr/hs/entrydsm/husky/domain/grade/service/GradeCalcService.java
  src/main/java/kr/hs/entrydsm/husky/domain/grade/service/GradeCalcServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/process/service/ProcessService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/Status.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/repositories/StatusRepository.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/UserInfoService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/UserStatusService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/UserTypeService.java
  src/test/java/hs/kr/entrydsm/husky/domain/grade/GradeCalcTest.java
Labels: enhancement, fix

#44 Hotfix: 출석점수 산출 시 NPE 예외처리
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/GraduatedApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/UnGraduatedApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/grade/service/GradeCalcServiceImpl.java
Labels: bug

#46 [Hotfix] 전형정보 업데이트 불가
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/repositories/async/GeneralApplicationAsyncRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/service/ApplicationService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/dto/SetUserInfoRequest.java
Labels: bug

#47 PDF Optimization: 원서출력 최적화 & 버그 수정
  src/main/java/kr/hs/entrydsm/husky/domain/grade/service/GradeCalcServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/grade/util/GradeUtil.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
  src/main/resources/templates/application.docx
  src/main/resources/templates/common_application.docx
  src/main/resources/templates/ged_application.docx
  src/main/resources/templates/preview/application.docx
  src/main/resources/templates/preview/common_application.docx
  src/main/resources/templates/preview/ged_application.docx
Labels: enhancement, fix

#49 Fix url and interface
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/UnGraduatedApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/service/ApplicationService.java
  src/main/java/kr/hs/entrydsm/husky/domain/application/service/ApplicationServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/image/service/ImageService.java
  src/main/java/kr/hs/entrydsm/husky/domain/image/service/S3ImageServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/process/service/ProcessService.java
  src/main/java/kr/hs/entrydsm/husky/domain/process/service/ProcessServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/schedule/service/ScheduleService.java
  src/main/java/kr/hs/entrydsm/husky/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/school/service/SchoolService.java
  src/main/java/kr/hs/entrydsm/husky/domain/school/service/SchoolServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/controller/UserInfoController.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/info/UserInfoService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/info/UserInfoServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/type/UserTypeService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/type/UserTypeServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/global/util/Validator.java
Labels: fix

#53 [HOTFIX] SlackMessageRequest DTO 분할
  src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/global/slack/SlackMessageRequest.java
  src/main/java/kr/hs/entrydsm/husky/global/slack/SlackSenderManager.java
  src/main/java/kr/hs/entrydsm/husky/global/slack/dto/Attachment.java
  src/main/java/kr/hs/entrydsm/husky/global/slack/dto/Field.java
Labels: bug, fix

#52 [HOTFIX] 학번이 공백일 경우 예외처리
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/GeneralApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/husky/global/util/Validator.java
Labels: bug

#60 Email param to Email body
  src/main/java/kr/hs/entrydsm/husky/domain/auth/controllers/AuthController.java
  src/main/java/kr/hs/entrydsm/husky/domain/auth/dto/request/EmailRequest.java
  src/main/java/kr/hs/entrydsm/husky/domain/auth/service/user/UserService.java
  src/main/java/kr/hs/entrydsm/husky/domain/auth/service/user/UserServiceImpl.java
Labels: fix

#61 Cloudfront url
  .github/workflows/deploy-to-registry.yml
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/kr/hs/entrydsm/husky/domain/image/service/ImageUrlService.java
  src/main/java/kr/hs/entrydsm/husky/domain/image/service/ImageUrlServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/image/util/PrivateKeyLoader.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/controller/UserInfoController.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/info/UserInfoService.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/info/UserInfoServiceImpl.java
  src/main/resources/application.yml
Labels: fix

#66 Fix school search
  src/main/java/kr/hs/entrydsm/husky/domain/application/domain/GeneralApplication.java
  src/main/java/kr/hs/entrydsm/husky/domain/image/service/ImageService.java
  src/main/java/kr/hs/entrydsm/husky/domain/image/service/S3ImageServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/process/service/ProcessServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/school/controller/SchoolController.java
  src/main/java/kr/hs/entrydsm/husky/domain/school/domain/repositories/SchoolRepository.java
  src/main/java/kr/hs/entrydsm/husky/domain/school/service/SchoolService.java
  src/main/java/kr/hs/entrydsm/husky/domain/school/service/SchoolServiceImpl.java
  src/main/java/kr/hs/entrydsm/husky/domain/user/service/info/UserInfoServiceImpl.java
Labels: bug, fix
